---
title: "Exploring_one_variavel.Rmd"
author: "Davi Laerte"
date: "22 de fevereiro de 2017"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

## Trabalhando com dados do Facebook


```{r dadosFacebook, echo=TRUE, message=FALSE}
# le dados do facebook
setwd('/home/davilaerte/Downloads')
dados <- read.csv('pseudo_facebook.tsv', sep = '\t')

# carrega bibliotecas e plota o grafico
library(ggplot2)

# plota grafico, com escalas de 1 a 31
qplot(x = as.factor(dob_day), data = dados) +
  scale_x_discrete(breaks = 1:31) +
  facet_wrap(~dob_month, ncol = 3)

```

## Contagem de Amigos

```{r}
# le dados do facebook
setwd('/home/davilaerte/Downloads')
dados <- read.csv('pseudo_facebook.tsv', sep = '\t')

# carrega bibliotecas e plota o grafico
library(ggplot2)

qplot(x = friend_count, data = dados)

```

## Limitando os eixos

```{r}
# uma forma
qplot(x = friend_count, data = dados, xlim = c(0,1000))

# outra forma
qplot(x = friend_count, data = dados) +
  scale_x_continuous(limits = c(0, 1000))

```

## ajustando largura e altura

```{r}
# ajusta largura e altura.
qplot(x = friend_count, data = dados, binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0,1000,50))

# numero de amigos por genero.
qplot(x = friend_count, data = dados, binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0,1000,50)) +
  facet_wrap(~gender)

# numero de amigos por genero, sem N/A.
qplot(x = friend_count, data = subset(dados, !is.na(gender)), binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0,1000,50)) +
  facet_wrap(~gender)

# dado uma variavel e uma variavel de categoria, e uma função
# para cada level da variavel de categoria, usa a função com a
# primeira variavel.
by(dados$friend_count, dados$gender, summary)

```


## dias de uso do Facebook

```{r}
# le dados do facebook
setwd('/home/davilaerte/Downloads')
dados <- read.csv('pseudo_facebook.tsv', sep = '\t')

# carrega bibliotecas e plota o grafico
library(ggplot2)

# plota grafico com dias de uso do facebook, por usuario
qplot(x = tenure , data = dados, binwidth = 30, color = I('black'), fill = I('#099DD9'))

# plota grafico com anos de uso do facebook, por usuario
qplot(x = tenure/365 , data = dados, binwidth = .25,
        xlab = 'Numero de anos usando o Facebook',
        ylab = 'Numero de usuarios da Amostra',
        color = I('black'), fill = I('#B8860B')) +
    scale_x_continuous(breaks = seq(0,7,1), limits = c(0,7))

```

## idades de quem usa o Facebook

```{r}
setwd('/home/davilaerte/Downloads')
dados <- read.csv('pseudo_facebook.tsv', sep = '\t')

# carrega bibliotecas e plota o grafico
library(ggplot2)

# plota grafico com as idades dos usarios.
qplot(x = age, data = dados, binwidth = 1,
      xlab = 'Idade dos usuarios',
      ylab = 'Numero de usuarios da Amostra',
       color = I('black'),
      fill = I('#228B22')) +
  scale_x_continuous(breaks = seq(0,115,5))
```

## trasformando dados

```{r}
setwd('/home/davilaerte/Downloads')
dados <- read.csv('pseudo_facebook.tsv', sep = '\t')

# carrega bibliotecas e plota o grafico
library(ggplot2)

# grafico normal
qplot(x = friend_count, data = dados)

# grafico com log de 10
qplot(x = log10(friend_count + 1), data = dados)

# grafico com raiz quadrada
qplot(x = sqrt(friend_count), data = dados)

# outra forma, grafico normal
ggplot(aes(x = friend_count), data = dados) + geom_histogram()

# outra forma, grafico com log 10
ggplot(aes(x = friend_count), data = dados) + geom_histogram() + scale_x_log10()

# outra forma, grafico com raiz quadrada
ggplot(aes(x = friend_count), data = dados) + geom_histogram() + scale_x_sqrt()
```


