---
title: "Explore_two_variables"
author: "Davi Laerte"
date: "3 de março de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## duas variaveis

```{r}
setwd('/home/davilaerte/Downloads')
dados <- read.csv('pseudo_facebook.tsv', sep = '\t')
library(ggplot2)

# plota grafico de ano por amigos
qplot(x = age, y = friend_count, data = dados)

# outro modo
ggplot(aes(x = age, y = friend_count), data = dados) + geom_point()

# plot com limite do eixo x
ggplot(aes(x = age, y = friend_count), data = dados) + geom_point() +
  xlim(13, 90)

# plot com ...
ggplot(aes(x = age, y = friend_count), data = dados) + 
  geom_point(alpha = 1/20) +
  xlim(13, 90)

# plot com geom_jitter
ggplot(aes(x = age, y = friend_count), data = dados) + 
  geom_jitter(alpha = 1/20) +
  xlim(13, 90)

# plot com geom_jitter, trasformando eixo y
ggplot(aes(x = age, y = friend_count), data = dados) + 
  geom_point(alpha = 1/20, position = position_jitter(h = 0), color = 'orange') +
  coord_trans(y = 'sqrt')    
```

## alpha and jitter solution

```{r}

# plot grafico de amigos iniciais vs idade.
ggplot(aes(x = age, y = friendships_initiated), data = dados) + 
  geom_point(alpha = 1/10) 

# plot grafico de amigos iniciais vs idade, com posição igual a jitter.
ggplot(aes(x = age, y = friendships_initiated), data = dados) + 
  geom_point(alpha = 1/10, position = 'jitter') 

# plot grafico de amigos iniciais vs idade, com posição igual a jitter
# e com trasformação de coordenada.
ggplot(aes(x = age, y = friendships_initiated), data = dados) + 
  geom_point(alpha = 1/10, position = position_jitter(h = 0)) +
  coord_trans(y = 'sqrt')
```

## medias condicionais 

```{r}
library(dplyr)
library(ggplot2)
# cria conjunto de dados agrupados, por grupo.
age_groups <- group_by(dados, age)

# cria novos dados a partir de um grupo, com novas varivaeis. 
dados.fc_by_age <- summarise(age_groups, friend_count_mean = mean(friend_count), friend_count_median = median(friend_count), n = n())

# ordena conjunto de dados, por uma variavel. 
dados.fc_by_age <- arrange(dados.fc_by_age, age)

head(dados.fc_by_age)

# plota grafico de idade por media de amigos, grafico de pontos.
ggplot(aes(age, friend_count_mean), data = dados.fc_by_age) + geom_point()


# plota grafico de idade por media de amigos, grafico de linha.
ggplot(aes(age, friend_count_mean), data = dados.fc_by_age) + geom_line()

```

## sobrepondo graficos

```{r}
# plot com geom_jitter, trasformando eixo y
ggplot(aes(x = age, y = friend_count), data = dados) + 
  geom_point(alpha = 1/20, position = position_jitter(h = 0), color = 'orange') +
  coord_trans(y = 'sqrt') + 
  geom_line(stat = 'summary', fun.y = mean) +
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = .1), linetype = 2, color = 'blue') + 
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = .5), color = 'blue') +
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = .9), linetype = 2, color = 'blue')
```

## correlacoes entre duas variaveis

```{r}
# calcula a correlação linear entre as variaves, idade e numero de amigos.
cor.test(dados$age, dados$friend_count, method = 'pearson')

# calcula a correlação linear entre as variaves, idade e numero de amigos
# para idades menores que 70
with(subset(dados, age < 70), cor.test(age, friend_count))
```


## criando grafico de dispersão

```{r}

# grafico de curtidas web por curtidas gerais.
ggplot(aes(x = www_likes_received, y = likes_received), data = dados) + geom_point()
  
# grafico com 95% dos dados
ggplot(aes(x = www_likes_received, y = likes_received), data = dados) + geom_point() + 
  xlim(0, quantile(dados$www_likes_received, 0.95)) +
  ylim(0, quantile(dados$likes_received, 0.95))

# grafico com funcção linear
ggplot(aes(x = www_likes_received, y = likes_received), data = dados) + geom_point() + 
  xlim(0, quantile(dados$www_likes_received, 0.95)) +
  ylim(0, quantile(dados$likes_received, 0.95)) +
  geom_smooth(method = 'lm', color = 'red')
```

## correlacao forte

```{r}
# correlacao linear curtidas web e curtidas gerais.
cor.test(dados$www_likes_received, dados$likes_received)
```



